// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRFGeXn8C9l6Iq0mHM1V0aADuuB0clRQ',
    appId: '1:289269615124:web:da4adedee0f154a9d77501',
    messagingSenderId: '289269615124',
    projectId: 'memo2-ca40b',
    authDomain: 'memo2-ca40b.firebaseapp.com',
    storageBucket: 'memo2-ca40b.firebasestorage.app',
    measurementId: 'G-1JB9T8Z17P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDpN9UvOJA2l5kuDaF4DxZtD_wkhDi1OI',
    appId: '1:289269615124:android:f2b0b9c7a0d273a1d77501',
    messagingSenderId: '289269615124',
    projectId: 'memo2-ca40b',
    storageBucket: 'memo2-ca40b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg2TsIBkIVfBJ5NhdCfPa1uE6iof2JEs0',
    appId: '1:289269615124:ios:466d9a21649ed89dd77501',
    messagingSenderId: '289269615124',
    projectId: 'memo2-ca40b',
    storageBucket: 'memo2-ca40b.firebasestorage.app',
    iosBundleId: 'com.example.memory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg2TsIBkIVfBJ5NhdCfPa1uE6iof2JEs0',
    appId: '1:289269615124:ios:466d9a21649ed89dd77501',
    messagingSenderId: '289269615124',
    projectId: 'memo2-ca40b',
    storageBucket: 'memo2-ca40b.firebasestorage.app',
    iosBundleId: 'com.example.memory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRFGeXn8C9l6Iq0mHM1V0aADuuB0clRQ',
    appId: '1:289269615124:web:7acd4bb71c1e591cd77501',
    messagingSenderId: '289269615124',
    projectId: 'memo2-ca40b',
    authDomain: 'memo2-ca40b.firebaseapp.com',
    storageBucket: 'memo2-ca40b.firebasestorage.app',
    measurementId: 'G-SBWKCNE9W3',
  );
}
